# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'movieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieDB
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'BouncyLayout', :git => 'https://github.com/pacu/BouncyLayout.git', :branch => 'swift5'
  pod 'GaugeKit', :git => 'https://github.com/pacu/GaugeKit', :branch => 'feature/Xcode10'
  pod 'SVProgressHUD'
  target 'movieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movieDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
